name: "sdl"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SDK_VERSION: 5.0.301

on:
  pull_request:
    branches: [develop]
    types: [assigned, opened, synchronize, reopened]

jobs:

  bindgen-job:
    name: "Bindgen"
    runs-on: ubuntu-latest
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: true

    - name: "Bindgen"
      shell: bash
      run: ./bindgen.sh

    - name: "Add + commit + push (if necessary)"
      uses: EndBug/add-and-commit@v7
      with:
        default_author: user_info
        message: "Update bindings"

  build-job:
    name: "${{ matrix.platform.rid }}"
    needs: [bindgen-job]
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows (x64), os: windows-latest, rid: win-x64 }
        - { name: Linux (x64), os: ubuntu-latest, rid: linux-x64 }
        - { name: macOS (x64), os: macos-latest, rid: osx-x64 }
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: true

    - name: "Build native library: Windows"
      if: ${{ startsWith(matrix.platform.rid, 'win') }}
      shell: pwsh
      run: .\library.cmd

    - name: "Build native lirbary: Unix"
      if: ${{ !startsWith(matrix.platform.rid, 'win') }}
      shell: bash
      run: ./library.sh

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_SDK_VERSION }}'

    - name: "Build .NET solution"
      run: dotnet build  --nologo --verbosity minimal --configuration Release

